### ISSUE TITLE
Can it be used for R3D?

### ISSUE THREAD

**Issue by leonguyen52** [ChocolateMilkGod/MiWifi-Language-Mod#1]
Since R3D and R3P is similar, except the internal 1TB HDD. Can I use it? Btw, the link in script is dead already, can you please fix it?

**Comment by p1u3o** [comment]
It needs to be a non-https link.

```
wget http://pastebin.com/raw/Zuk7En96 -O install.sh
```

I have swapped the firmware on my device to OpenWRT, so I no longer use this mod.

**Comment by p1u3o** [comment]
This has been updated.

**Comment by bethnard** [comment]
Hello,

Sorry to come back to this post, especially that now you're using OpenWRT directly, but I've a R3D and would like to use your code here. 

Checking the base.en.lmo files, I could only find R3P and R3G. When I checked the code, it is pointing out directly to the R3G. Would it also work on my R3D or should I point the link to the R3P's "base.en.lmo"?

Thanks.
